<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Job Description_jobTitlejobDescription</name>
   <tag></tag>
   <elementGuidId>c70d8983-e54c-4dd2-90d9-a4e0ba2825ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jobTitle_jobDescription</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='jobTitle_jobDescription']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>45d0c5fc-b81d-4198-947a-86b59fdc1dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>d6d4d584-4aa6-4889-b3e0-ddcb340b064b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>8b90b07e-b966-449c-a662-d9be0db112f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jobTitle[jobDescription]</value>
      <webElementGuid>742673bc-22bd-428e-9243-251e81ccbf4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>400</value>
      <webElementGuid>23de9acc-4648-43a5-b79b-37dce185325d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jobTitle_jobDescription</value>
      <webElementGuid>a68006a0-c9df-4d44-b80b-13d984decfcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobTitle_jobDescription&quot;)</value>
      <webElementGuid>5bdcd1da-45a4-4d53-9c2f-a81b5c5bf4be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='jobTitle_jobDescription']</value>
      <webElementGuid>025e73fb-e2a7-41d5-84d5-7d837550ebc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSavejobTitle']/fieldset/ol/li[2]/textarea</value>
      <webElementGuid>2af0194e-b655-40a9-90a2-2e9942b4208c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>1728fd40-b393-49dd-bcc6-110de5dfe84b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'jobTitle[jobDescription]' and @id = 'jobTitle_jobDescription']</value>
      <webElementGuid>96de3cb5-57a5-409b-b3df-91bcb2566a4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
