<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Note_jobTitlenote</name>
   <tag></tag>
   <elementGuidId>10c063b0-22d2-4b51-b22e-e25568d5f974</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jobTitle_note</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='jobTitle_note']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4e277b85-f5c9-46a4-80b7-56cdc0807fc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>8b64a3c9-42fe-4847-821a-a2695de965ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>027282e7-8cb3-4dc8-9ee9-ecaf5fc9fc71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jobTitle[note]</value>
      <webElementGuid>eab8ba6d-5b2e-4c0c-a06e-f6fbd8b73e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jobTitle_note</value>
      <webElementGuid>6d47a93c-0785-46bf-861f-fdfcad7e4f6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobTitle_note&quot;)</value>
      <webElementGuid>d544308a-ffd4-4943-a2c0-a2eb4be89f03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='jobTitle_note']</value>
      <webElementGuid>761fa3ab-c445-44bb-8332-8aa1c20629df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmSavejobTitle']/fieldset/ol/li[4]/textarea</value>
      <webElementGuid>6c84435a-89ce-4c2e-adb8-af97ed92afad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/textarea</value>
      <webElementGuid>f52c7ae0-e3c2-4ca4-8e4d-a958c03bf265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'jobTitle[note]' and @id = 'jobTitle_note']</value>
      <webElementGuid>3be08fb5-13b0-47e6-94d6-d429316ea08f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
