<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Malaysian Ringgit</name>
   <tag></tag>
   <elementGuidId>e44e4132-838b-4f1c-b137-f8221d1d38d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.editLink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tblCurrencies']/tbody/tr/td[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0f2d33f6-b53e-4a1c-8091-01e6c7bc39cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>b2560225-3dfa-44f8-a4c0-2c18ca0a9435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editLink</value>
      <webElementGuid>96128900-7581-41aa-a563-3d6eb5eac601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Malaysian Ringgit</value>
      <webElementGuid>0da8758f-ef92-49eb-9bd8-504098cf19f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tblCurrencies&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[2]/a[@class=&quot;editLink&quot;]</value>
      <webElementGuid>d75a6cfd-1928-407a-ba3d-ab86444a2c69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblCurrencies']/tbody/tr/td[2]/a</value>
      <webElementGuid>8c8e7ff0-e29c-4943-bc0d-7a620b583b77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Malaysian Ringgit')]</value>
      <webElementGuid>cdb3f459-64e9-4477-a16b-ba02745fe3f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maximum Salary'])[2]/following::a[1]</value>
      <webElementGuid>970ff32c-3199-4c54-acdc-213ee2c08818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Minimum Salary'])[2]/following::a[1]</value>
      <webElementGuid>2101699e-e800-4380-85e7-d57074d640ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OrangeHRM, Inc'])[1]/preceding::a[1]</value>
      <webElementGuid>1cd37e54-c452-415a-866a-02442288f780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Malaysian Ringgit']/parent::*</value>
      <webElementGuid>79f6c1b9-0038-4f3d-b9ac-efc7d3ef9937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[20]</value>
      <webElementGuid>697825cd-baaf-4f38-81d6-c38e59eb1e81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a</value>
      <webElementGuid>43b9762e-4e84-45ad-9e02-4fb8c8c5848a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Malaysian Ringgit' or . = 'Malaysian Ringgit')]</value>
      <webElementGuid>16f22a6a-ac4d-441d-9fb7-a0086ab7ba42</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
