<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__payGradeCurrencycurrencyName</name>
   <tag></tag>
   <elementGuidId>907d16f3-dccf-46e1-ada5-6620f2dc114e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#payGradeCurrency_currencyName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payGradeCurrency_currencyName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>44f0901c-8c2b-478f-b677-5dfcf123ead4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6dd24487-25fa-43d7-9713-a08134058c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payGradeCurrency[currencyName]</value>
      <webElementGuid>9e051eab-201d-467f-babf-9e539e6a85cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formInput ac_input</value>
      <webElementGuid>87aa85ab-3ace-4d85-8afc-95a2dff53e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>52</value>
      <webElementGuid>b8dc0fb6-aeee-4efa-ba41-31231a409d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payGradeCurrency_currencyName</value>
      <webElementGuid>3d2608ca-2cf8-4ccf-b013-0b9adc5858c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e24bfb4c-e690-47c6-a337-2cc027a1d4d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payGradeCurrency_currencyName&quot;)</value>
      <webElementGuid>243513be-594d-42cf-97ba-cf7947a8e388</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payGradeCurrency_currencyName']</value>
      <webElementGuid>b4a2c1a7-1ef3-43d1-ac55-6c7083c91da3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ol[@id='addPaneCurrency']/li/input</value>
      <webElementGuid>1517200b-5025-41d5-bbd4-bc427e0bef5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/form/fieldset/ol/li/input</value>
      <webElementGuid>a9eeff16-78de-4e1a-bd3a-02a06afb06cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'payGradeCurrency[currencyName]' and @id = 'payGradeCurrency_currencyName']</value>
      <webElementGuid>53652608-bac7-407f-af81-800b1c98c0a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
