<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Minimum Salary_payGradeCurrencyminSalary</name>
   <tag></tag>
   <elementGuidId>f2cc68dd-e2a7-4237-be2c-74463e9cd9b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#payGradeCurrency_minSalary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payGradeCurrency_minSalary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>21f5a876-5eda-4d0c-8ac8-999b35d126ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a166a41c-45e9-4b65-ada3-c2f3dc548db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payGradeCurrency[minSalary]</value>
      <webElementGuid>2ae4c85f-d8c3-4c5b-8b03-5139fc389f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formInput</value>
      <webElementGuid>3230e2c8-d56a-4e96-aa35-5ae619194a66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>52</value>
      <webElementGuid>a03f2a6e-7e85-482d-adc5-48178dea8489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payGradeCurrency_minSalary</value>
      <webElementGuid>27e675a5-4b13-4306-b7b3-c54c7f1516cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payGradeCurrency_minSalary&quot;)</value>
      <webElementGuid>8144c43e-f8f0-480a-afa7-9d9fd82258e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payGradeCurrency_minSalary']</value>
      <webElementGuid>68f3c3e3-f261-4694-8901-1084b9b4c08a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ol[@id='addPaneCurrency']/li[2]/input</value>
      <webElementGuid>b8651eaf-0422-48fe-a107-b93edfb88209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/input</value>
      <webElementGuid>761cb16b-e019-465b-aa74-7d44341b4f25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'payGradeCurrency[minSalary]' and @id = 'payGradeCurrency_minSalary']</value>
      <webElementGuid>ff3bd883-5e25-47ff-86aa-b0de7ae9a489</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
