<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__btnSaveCurrency</name>
   <tag></tag>
   <elementGuidId>f4da573b-c690-4190-aa7a-828bd96cec69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnSaveCurrency</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnSaveCurrency']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f19bd80-1a45-4a7f-8595-a19c1e0e77ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>227f52e9-e703-48db-8772-1be4dd20ec65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>addbutton hover</value>
      <webElementGuid>b349ef02-e204-46e1-9eb3-2edb7eb7c9d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnSaveCurrency</value>
      <webElementGuid>bbba040b-075a-433b-b731-0e5d54960aaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSaveCurrency</value>
      <webElementGuid>ded2afab-1185-4d2d-88d5-6e5b7cdbe25c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>ed007465-7636-4b6c-89e7-796345db5a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSaveCurrency&quot;)</value>
      <webElementGuid>1e59289c-60b5-4c9c-b30c-fdca06bfc700</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnSaveCurrency']</value>
      <webElementGuid>b9448711-dee8-46ea-9c32-9fd40d1648e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='actionButtons']/input</value>
      <webElementGuid>de991d32-719b-4095-8625-48c79a87d112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/form/fieldset/p/input</value>
      <webElementGuid>004aa126-5d0f-4a7a-b49e-c70e6de1b8de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'btnSaveCurrency' and @id = 'btnSaveCurrency']</value>
      <webElementGuid>5f61221a-962b-4d29-84c1-9d76b053fe02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
