<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__jobCategoryname</name>
   <tag></tag>
   <elementGuidId>2278ff05-ad7b-428a-82a2-886989a44955</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#jobCategory_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='jobCategory_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a85171c-8afc-4918-a300-b38b7489644f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>51b038eb-52ab-4ede-b91f-e604910d8b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>jobCategory[name]</value>
      <webElementGuid>fbc7ff39-7bf1-42ca-8555-74444378e67d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formInput</value>
      <webElementGuid>19e28d8b-84ca-412c-a949-600900953810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>52</value>
      <webElementGuid>92339256-4ea0-4956-8a28-9fff003d9bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jobCategory_name</value>
      <webElementGuid>a5d41728-cf4c-404c-8af5-fb3da1bc17e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jobCategory_name&quot;)</value>
      <webElementGuid>619798cd-40a9-4087-b436-fb2f803d4a75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='jobCategory_name']</value>
      <webElementGuid>1f1ab193-6648-4636-9535-235feb7ea4d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmJobCategory']/fieldset/ol/li/input</value>
      <webElementGuid>6317bf7d-dece-457a-98b8-036af15b4349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>34a7561a-2f4a-46ab-9349-d0879f3f81f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'jobCategory[name]' and @id = 'jobCategory_name']</value>
      <webElementGuid>dfe8c950-05a7-4199-b017-ac3d80332446</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
