<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__payGradename</name>
   <tag></tag>
   <elementGuidId>f55276c1-6077-472e-9fcb-7e8e0d8e8d02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#payGrade_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payGrade_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b5211a48-cd49-4720-b7fe-ef8d3d36cd60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6c3e6860-4f7f-42c5-85f4-8b10cf1a14f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payGrade[name]</value>
      <webElementGuid>27d3c720-ab41-47c4-9cd5-77c9f7c486c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payGrade_name</value>
      <webElementGuid>612cec1b-29f4-441d-a9a9-8f3d1d874578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payGrade_name&quot;)</value>
      <webElementGuid>ae510790-0de8-44ff-8d3c-b1e1cf9f835e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payGrade_name']</value>
      <webElementGuid>fd6bdd48-0074-42bf-ba00-4cd3d557828d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmPayGrade']/fieldset/ol/li/input</value>
      <webElementGuid>3b233f45-85e5-4445-89fa-9ccbf4f687be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>8b2bbbcb-38e2-4fa1-be18-072c1cff06e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'payGrade[name]' and @id = 'payGrade_name']</value>
      <webElementGuid>0090b124-7fae-4ffe-b0db-0bc7fb6bc18e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
