<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Assigned Currencies_currencyCheckAll</name>
   <tag></tag>
   <elementGuidId>a05450cb-fb9a-4deb-a74d-582956fc1790</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#currencyCheckAll</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='currencyCheckAll']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe4024d0-7b2d-4581-82a3-c31032a5eef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>3b2d6bbd-2522-491e-a373-c7dfff837f67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>currencyCheckAll</value>
      <webElementGuid>538f5daf-6271-4ef5-9270-9911e79e37f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkboxCurr</value>
      <webElementGuid>965a589b-c03a-499d-924c-b94d70b7ffe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;currencyCheckAll&quot;)</value>
      <webElementGuid>273e1de5-b41f-4894-aad6-07b9a1a04671</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='currencyCheckAll']</value>
      <webElementGuid>687a3503-f287-4c7d-83b8-20d53b01a699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblCurrencies']/thead/tr/th/input</value>
      <webElementGuid>f34e8015-c364-435b-9232-04f5365b4806</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/input</value>
      <webElementGuid>dfcdae4d-8f75-4078-990f-ce06a07a1869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'currencyCheckAll']</value>
      <webElementGuid>0c34ed46-3273-4e4a-a6e2-0e3fd6dd8dc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
