<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__payGradeCurrencycurrencyName</name>
   <tag></tag>
   <elementGuidId>7f0bf9ec-3dba-462b-9f29-4d86f3c6bad0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#payGradeCurrency_currencyName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payGradeCurrency_currencyName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db7b73da-ed10-4b5e-94a3-ffcba0e90b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9b587872-2814-403f-ac86-0274804158b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payGradeCurrency[currencyName]</value>
      <webElementGuid>bae46e73-f80f-4af2-a0d6-e25f4a717e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formInput ac_input</value>
      <webElementGuid>66eb6c8c-d25d-4fdc-b0b9-51ea8890319f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>52</value>
      <webElementGuid>e848e3eb-1577-44d3-b52f-7a3df31c64fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payGradeCurrency_currencyName</value>
      <webElementGuid>f657c6c7-f7ce-4034-b123-d106e203aa40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b894a037-e351-43de-bfbf-ccd3a40cf916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payGradeCurrency_currencyName&quot;)</value>
      <webElementGuid>865ed5a9-4b66-41c1-abca-b7fcb3fd32f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payGradeCurrency_currencyName']</value>
      <webElementGuid>df2ca142-dbde-4981-bcd8-ad2046860dd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ol[@id='addPaneCurrency']/li/input</value>
      <webElementGuid>58ecd0a9-9a83-4203-9a9c-56bfde3a651a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/form/fieldset/ol/li/input</value>
      <webElementGuid>37df558b-cd46-4966-90ca-65b1b750bd83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'payGradeCurrency[currencyName]' and @id = 'payGradeCurrency_currencyName']</value>
      <webElementGuid>184f2d53-4bab-4bcb-bf09-2d8d72dcc3e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
