<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Minimum Salary_payGradeCurrencyminSalary</name>
   <tag></tag>
   <elementGuidId>d5044420-d400-4de2-9120-5149936e79e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#payGradeCurrency_minSalary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payGradeCurrency_minSalary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>44d457f0-68ed-428a-aad2-02b03a381e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>72ffc4a6-a74c-4a10-a106-352dfffe93e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payGradeCurrency[minSalary]</value>
      <webElementGuid>026c1c60-e5a1-47d3-b72d-9c052ee50b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formInput</value>
      <webElementGuid>c6a27758-3d49-44a2-9c16-742c2a6c560c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>52</value>
      <webElementGuid>ef131412-bcf1-483b-b289-61ef906c3914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payGradeCurrency_minSalary</value>
      <webElementGuid>5aeb59aa-bfba-4890-a408-b3869d0300fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payGradeCurrency_minSalary&quot;)</value>
      <webElementGuid>e4f311e4-ace9-490d-ad03-fdbf949821b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payGradeCurrency_minSalary']</value>
      <webElementGuid>4c9c8906-771d-40d0-a33c-6f25be1ac19c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ol[@id='addPaneCurrency']/li[2]/input</value>
      <webElementGuid>2c0d1365-447c-4794-be55-4c6e7ef826a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/input</value>
      <webElementGuid>2144080a-a1bf-42da-9184-083be902cab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'payGradeCurrency[minSalary]' and @id = 'payGradeCurrency_minSalary']</value>
      <webElementGuid>d998f3c6-36f2-4106-b7bc-47c4509f564a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
