<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__btnSaveCurrency</name>
   <tag></tag>
   <elementGuidId>3c214fb2-a3e8-4e4a-8622-09271d0a7bd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnSaveCurrency</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnSaveCurrency']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>015dc785-1e7b-45e7-acb5-75fe41b7e85c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dc68a6cd-9f09-4549-9249-d2e9b1d1356c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>addbutton hover</value>
      <webElementGuid>8d3e1be8-4c3e-46ee-946c-7d12f32a4605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btnSaveCurrency</value>
      <webElementGuid>c3f6b43c-8f9a-44d2-94b7-8db6eebd6a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSaveCurrency</value>
      <webElementGuid>6fe38520-e349-49d2-8efc-89491d019fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>34dee5ba-287a-4d9d-be75-8786b281fcc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSaveCurrency&quot;)</value>
      <webElementGuid>17f99e59-5075-41bc-8bf7-cede0dd6b1d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnSaveCurrency']</value>
      <webElementGuid>14a4abca-bd40-484e-92c2-d68a62332525</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='actionButtons']/input</value>
      <webElementGuid>c6e7f3f7-7277-40cd-adf3-96b5438af054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/form/fieldset/p/input</value>
      <webElementGuid>97a1547d-4249-48b3-8923-5312fa283571</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @name = 'btnSaveCurrency' and @id = 'btnSaveCurrency']</value>
      <webElementGuid>f4f8ce56-95a9-47e1-84e3-a82f916f13ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
