<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Assigned Currencies_btnAddCurrency</name>
   <tag></tag>
   <elementGuidId>b2ab8d93-84b2-4d5d-9dd9-b1f2d32a0845</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnAddCurrency</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='btnAddCurrency']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>89150fc1-b494-42fd-a24e-8b3eeba1f1bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>54cd96df-45bd-4b47-82f4-ed6d1d20a452</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>addbutton hover</value>
      <webElementGuid>ecde201f-6aa0-4db0-b2fe-b6666e4cb17e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnAddCurrency</value>
      <webElementGuid>f4c68a9f-9cfc-4029-b047-bac66d68cb7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>b5b729de-526f-4b5c-addd-503cd2160ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnAddCurrency&quot;)</value>
      <webElementGuid>e6a6a46c-bb33-4bf8-ae91-6e037c20a1aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='btnAddCurrency']</value>
      <webElementGuid>aec9100f-3b10-4fb7-b8e1-b47289cadca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='addDeleteBtnDiv']/input</value>
      <webElementGuid>8ee6947d-922e-4a99-a231-b3a623e0ce5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/p/input</value>
      <webElementGuid>a9b60001-cfbc-48f2-bf94-3740866df139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'btnAddCurrency']</value>
      <webElementGuid>ef748598-a61b-4955-87a3-54117648b73f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
