<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enabled_chkSelectRow</name>
   <tag></tag>
   <elementGuidId>ea363220-c82c-4673-8891-9f842664aa0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ohrmList_chkSelectRecord_49</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ohrmList_chkSelectRecord_49']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cdeb1e35-9767-4f81-b626-547328a662c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>caa5e73a-7e35-4569-b9ec-9a645db304ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ohrmList_chkSelectRecord_49</value>
      <webElementGuid>591b7821-91d8-4b25-be22-f45b696d1650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chkSelectRow[]</value>
      <webElementGuid>936c13b9-c0c2-4a12-90b5-c259ef2566c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>49</value>
      <webElementGuid>c151d5d2-fe16-4342-8735-f909ff76ded7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ohrmList_chkSelectRecord_49&quot;)</value>
      <webElementGuid>005ab9fb-91fe-483b-9008-652a37b093fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ohrmList_chkSelectRecord_49']</value>
      <webElementGuid>31b556e2-6b85-4fbb-8f24-c4dd076667f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='resultTable']/tbody/tr[47]/td/input</value>
      <webElementGuid>dd3299b9-4fbe-4825-ac2c-05e22a212580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[47]/td/input</value>
      <webElementGuid>3e7de149-a479-49f1-a431-0a06f89aaf5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'ohrmList_chkSelectRecord_49' and @name = 'chkSelectRow[]']</value>
      <webElementGuid>f3d83edf-e3ba-491e-b3ba-faf1e253ab3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
