<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Technicians_chkSelectRow</name>
   <tag></tag>
   <elementGuidId>b0f8c051-4372-482a-abd2-84ffac97658d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ohrmList_chkSelectRecord_10']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ohrmList_chkSelectRecord_10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2296fc46-62c5-48dd-8479-06206655090f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7c511f3e-8cca-4d7a-8ce9-ae845e3bc7d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ohrmList_chkSelectRecord_10</value>
      <webElementGuid>d2849603-432c-46f8-bf00-91552d9b4c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chkSelectRow[]</value>
      <webElementGuid>b7e1250b-9e0d-44ca-9060-de2e47eaed86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>11f5b646-827d-4d21-ab93-f2b450194c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ohrmList_chkSelectRecord_10&quot;)</value>
      <webElementGuid>65d05ea0-a4e5-4baa-babe-63ea0af6225a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ohrmList_chkSelectRecord_10']</value>
      <webElementGuid>a8357a1c-3938-4547-aa8b-1990c22a0ce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='resultTable']/tbody/tr[10]/td/input</value>
      <webElementGuid>85760daa-9838-4c23-aca4-690bb7d323c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td/input</value>
      <webElementGuid>a8b7f2ea-7c20-4b31-9843-2a4a40ff91c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'ohrmList_chkSelectRecord_10' and @name = 'chkSelectRow[]']</value>
      <webElementGuid>980bb3a0-c96e-4f0c-8005-890b7e7207d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
