<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__empStatusname</name>
   <tag></tag>
   <elementGuidId>f79f0a24-1aa0-453c-b01d-aed3d3db5660</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#empStatus_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='empStatus_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d50999c3-a7eb-425d-8b09-5c6c5ca2291a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fd362879-43d6-40d4-ba4e-b14745b828c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>empStatus[name]</value>
      <webElementGuid>045d0d01-7a8e-49fe-9a2d-b2d66f2f64be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formInput</value>
      <webElementGuid>e5f7d222-3f89-4cfb-938d-ff03e2f30ee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>52</value>
      <webElementGuid>359969b7-789c-411c-9af2-46ee5cb5658b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>empStatus_name</value>
      <webElementGuid>e66e029e-0b10-4721-9361-8477cc0e564b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;empStatus_name&quot;)</value>
      <webElementGuid>1473b5de-968b-4855-a9a1-c81d7fd1dc64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='empStatus_name']</value>
      <webElementGuid>651106e8-ae21-413b-a299-c89437b50c8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frmEmpStatus']/fieldset/ol/li/input</value>
      <webElementGuid>7ea383dc-3333-4cb8-9e0c-d6b84b44e809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>f1d7572d-4c38-4e30-91cb-9aeeabb4f76b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'empStatus[name]' and @id = 'empStatus_name']</value>
      <webElementGuid>43b1d69d-7520-4306-8b96-fffc1ee75132</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
